[package]
name = "bigint"
version = "0.1.0"
edition = "2021"

[lib]
name = "bigint"

[dependencies.pyo3]
version = "0.19.0"
features = ["extension-module"]
optional = true

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "biguint"
harness = false
