[project]
name = "bigint"
dependencies = [
"exceptiongroup==1.1.1",
"iniconfig==2.0.0",
"maturin==1.1.0",
"packaging==23.1",
"pluggy==1.0.0",
"pytest==7.3.2",
"tomli==2.0.1",]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3"]
